INSERT INTO recording (id, recording_url, title, owner_id, recording_type, transcript, recorded_date, duration, recording_start_time, recording_end_time, sub_transcripts, translated_transcript) 
VALUES (99, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1727206702/EchoTranscript/stcxtfxaaszwwal2uusf.mp3', 'First Recording', 1, 'RECORDED', 101, '2023-09-01 00:00:00', 300, '2023-09-01T00:00:00', '2023-09-01T00:01:00', 201, 301),
       (101, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1733987237/Eco-Transcribe/file.mp3', 'second test', NULL, 'UPLOADED', NULL, '2024-12-05 16:06:20', NULL, NULL, NULL, NULL, NULL),
       (102, 'http://res.cloudinary.com/dscjf5irc/video/upload/v1735166915/Eco-Transcribe/k2pjjs8ptyoqybdvjfer.mp3', 'audio_11.mp3', NULL, 'UPLOADED', 102, '2024-12-25T22:48:35', NULL, NULL, NULL, NULL, NULL);
-- (2, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1727206702/EchoTranscript/stcxtfxaaszwwal2uusf.mp3', 'Second Recording', 2, 'recorded', 102, '2023-09-02', 600, '2023-09-02 11:00:00', '2023-09-02 11:10:00', 202, 302),
-- (3, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1727206702/EchoTranscript/stcxtfxaaszwwal2uusf.mp3', 'Third Recording', 1, 'uploaded', 103, '2023-09-03', 450, '2023-09-03 12:00:00', '2023-09-03 12:07:30', 203, 303),
-- (4, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1727206702/EchoTranscript/stcxtfxaaszwwal2uusf.mp3', 'Fourth Recording', 3, 'link', 104, '2023-09-04', 750, '2023-09-04 13:00:00', '2023-09-04 13:12:30', 204, 304);



INSERT INTO transcript (transcript_id, recording_id, text, summary, language)
VALUES (99, 99, 'Recording 3. 1. Im not sure, but I think it starts with an F. 2. No, I am pretty sure its double L. 3. Is that M for Mary? 4. Sorry, was that last letter a T or a C? 5. Do you know if its spelt with a ch or sh?', null, 'English'),
       (102, 102, 'Recording 11. Listening section one. Hi, Sam. Wed better start planning the party. Its in less than two weeks, isnt it? Yeah, I guess it is. There isnt much to do, is there? Well, we need to sort out food for a start. Why dont we just order some pizzas? But we always do that. Lets do something a bit different. Besides, its pretty expensive. Mmm. What about a barbecue, then? Or we could just do hot dogs. Hmm. Too much preparation involved. There are a lot coming, you know. Sandwiches, then. Thats easy enough. Sandwiches. Thats a good idea. Hmm. Hang on. That would be even more preparation than the barbecue. Better go back to the original idea. I suppose. Pizza it is, then. Now, we also need to think about music and invitations. Well, we dont need to buy invitations. I think we should just do them on the computer and keep costs down. Good idea. And what about music? We can just use the same stuff we had last time. Its fine. Ok. Well, if we dont let people know soon, there wont be anyone there, so lets make that our priority. Have you got your laptop? Yeah. Told you there wasnt much to do. Listening Section three. Hi, Julie. Have you got time to plan our project? Sure. Ive got a few minutes. We need to choose a topic based on the theme of pollution, dont we? Thats right. Have you got any preferences? Well, I did a huge assignment on water pollution last year, so we could just do that. Actually, the tutor did make a point of saying not to use last years materials, so wed better not. Its probably a bit out of date now, anyway. Also, it focused specifically on industry and I think were supposed to take a broad view. Thas right. We could look at something totally different, like the effects of fumes on air quality. Hmm, good idea. And we could make sure we include all of the sources like traffic and factories. So what else do we need to do? Shall we go to the library and look for resources? Actually, I think wed be better off looking online. The good resources in the library are often all out at this time of the year. Anyway. Before we notify the tutor which topic weve chosen, I think we need to ask the others what theyre doing. Youre right. We need to make sure were not all doing the same thing. Lets ask them this afternoon in the tutorial. Great idea.', null, 'English');

--        (101, 'https://res.cloudinary.com/dscjf5irc/video/upload/v1733987237/Eco-Transcribe/file.mp3', 'second test', NULL, 'UPLOADED', NULL, '2024-12-05 16:06:20', NULL, NULL, NULL, NULL, NULL);